http:
  routers:
    dashboard:
      rule: "Host(`dashboard-uat.pideYcuenta.com`)"
      entryPoints:
        - websecure
      service: dashboard_svc
      tls:
        certResolver: cloudflare

  services:
    dashboard_svc:
      loadBalancer:
        servers:
          - url: "http://dashboard:80"
